version: '3.7'

services:
  doc-builder:
    container_name: doc_builder
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: aptitude/wp4_d4.1
    volumes:
      - .:/D4.1
